name       : perl-tie-simple
version    : 1.04
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HANENKAMP/Tie-Simple-1.04.tar.gz : 29e9e2133951046c78f205f1b3e8df62c90e114f0e08fa06b817766a0f808b12
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Variable ties made easier, much, much, much easier...
description: |
    This module adds the ability to quickly create new types of tie objects without creating a complete class. It does so in such a way as to try and make the programmers life easier when it comes to single-use ties.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
